#!/usr/bin/env bash

[ "$1" -gt 0 ] && ~/.config/dunst/dunstify/restarted_notif i3wm &

icon_theme_path="/home/$USER/.local/share/icons/Gruvbox-Material-Dark-OneColored"

desc="$1"
desc=${desc:-"x"}

icon="$icon_theme_path/16x16/apps/system-restart.svg"

dunstify \
	-i "$icon" \
	"Restarted:" \
	"$desc"
